### ISSUE TITLE
QBCore Framework

### ISSUE THREAD

**Issue by balcer64** [renzuzu/renzu_vehicleshop#10]
does not work with the base platform, the problem is as follows: if you get out of the car after the purchase, you cannot return to it, there is no key. If you immediately send it to the garage and put the car in, then after removing the car from the garage, the key will appear

**Comment by balcer64** [comment]
[38;5;124m[script:renzu_vehicle] BUYING START	youga2
[38;5;124m[script:renzu_vehicle] BUYING VEHICLES SAVED FROM SQL vehicles tables
[38;5;124m[script:renzu_vehicle] RESULT FETCHED
[38;5;124m[script:renzu_vehicle] BUY DONE
[38;5;124m[script:renzu_vehicle] Sending Keys
[38;5;124m[script:renzu_vehicle] SENDING TO CLIENT SUCCESS

**Comment by Ademo93** [comment]
try this : server/server.lua =

function GenPlate(prefix)
    local plate = LetterRand()..''..NumRand()
    if prefix then plate = prefix..' '..NumRand() end
    if temp[plate] == nil then
        return plate
    end
    Wait(1)
    print(plate)
    return GenPlate(prefix)
end

function LetterRand()
    local emptyString = {}
    local randomLetter;
    while (#emptyString < 6) do
        randomLetter = GetRandomLetter(1)
        table.insert(emptyString,randomLetter)
        Wait(0)
    end
    local a = string.format("%s%s%s%s", table.unpack(emptyString)):upper()  -- "2 words"
    return a
end

function NumRand()
    local emptyString = {}
    local randomLetter;
    while (#emptyString < 6) do
        randomLetter = GetRandomNumber(1)
        table.insert(emptyString,randomLetter)
        Wait(0)
    end
    local a = string.format("%i%i%i%i", table.unpack(emptyString))  -- "2 words"
    return a
end

**Comment by DopeLovingHippy** [comment]
im having a similar issue using Qb-vehiclekeys won't give me te keys after buying car ....also love ur scripts man . been using ur HUD and Projectcars also fuel

**Comment by DopeLovingHippy** [comment]
NVM fixed it by changing plate space

**Comment by DonnyChooch** [comment]
can anyone give me a hand setting these up for qb?

**Comment by XxDeezixX** [comment]
im having this same problem anyone can help? JS keys and QBCORE.... thank you..
