### ISSUE TITLE
Police Shop

### ISSUE THREAD

**Issue by RestrictedNova** [renzuzu/renzu_vehicleshop#18]
The police shop seems to not wanna open at all but everything else works good as far as i know, fresh install set to QBCORE.

I get this error in the server terminal - 
`[script:renzu_vehicle] SCRIPT ERROR: @renzu_vehicleshop/server/server.lua:34: attempt to compare number with table`

**Comment by renzuzu** [comment]
https://github.com/renzuzu/renzu_vehicleshop/commit/540e681ad0444bf9a9465c813dc3adb2ab7f8fba

**Comment by RestrictedNova** [comment]
You're a legend mate
