### ISSUE TITLE
[Bug] cannot load the interface to buy a vehicle

### ISSUE THREAD

**Issue by Dokman** [renzuzu/renzu_vehicleshop#19]
i've inserted by myself some addon cars, that they are at sportsclassics category so should'nt have any kind of problem

![image](https://user-images.githubusercontent.com/2290904/139857192-214d6d91-be5b-496e-89b6-fd94012af1f0.png)

**Comment by renzuzu** [comment]
sql Vehicles table  category column must not be nil

**Comment by Dokman** [comment]
my kind of query
INSERT INTO `vehicles` (`name`, `model`, `price`, `category`) VALUES ('Mazda RX-7 FD3S', 'fd', '200000', 'sportsclassics');

**Comment by Dokman** [comment]
my fault a non named vehicle was there and that was causing to not load
