### ISSUE TITLE
Selling a vehicle doesn't work if plate has spaces in between characters

### ISSUE THREAD

**Issue by TheSpartaPT** [renzuzu/renzu_vehicleshop#20]
hey, i spotted a problem with your vehicleshop where if you set the vehicle plates to have spaces in between characters your DELETE query doesn't actually delete anything because you're doing this: 

```lua
string.gsub(plate:upper(), ' ', '')
```

which replaces every space with nothing

funny thing is you're doing it the right way inside your 'renzu_vehicleshop:sellvehicle' event in your select query, all you have to do to fix it is replace that with this:

```lua
string.gsub(plate:upper(), '^%s*(.-)%s*$', '%1')
```

**Comment by renzuzu** [comment]
push a PR?
this might be correct as old gsub method still exist..

**Comment by ttechr** [comment]
I am having this same issue. When a player sells a vehicle it doesnt delete it from the database. I tried to change the plate to not include a space, but that didnt do anything.

**Comment by Emono78** [comment]
Thanks for the fix but heads up it had to be slightly modified to get it working for me. 
`string.gsub(plate:upper(), '^%s*(.-)%s*$', '%1')})`
