### ISSUE TITLE
Error on fresh install

### ISSUE THREAD

**Issue by LoomBands** [renzuzu/renzu_vehicleshop#24]
Hi. Not sure why but I seem to be getting this error on a clean install.

![image](https://user-images.githubusercontent.com/93899835/140688931-f11c4364-4c95-4186-8d88-28aa32597f72.png)
![image](https://user-images.githubusercontent.com/93899835/140688985-0f9246c5-220b-434f-a72c-0f89322fcfac.png)

![image](https://user-images.githubusercontent.com/93899835/140689082-68f24eff-da88-45be-876d-4ef31f2aa2b7.png)

**Comment by Velkostatkar** [comment]
you have a wrong version I check a line on Githib and its different and you also post garage issue into vehicle shop room. Just download MAIN i gess is the correct one

**Comment by renzuzu** [comment]
This was fixed thank you
