### ISSUE TITLE
Not able load with oxmysql

### ISSUE THREAD

**Issue by Velkostatkar** [renzuzu/renzu_vehicleshop#25]
Hi, when you using oxmysql and have all your scripts the OXMYSQL going to time out due vehicleshop. I fix it in my server config by put ::

connectTimeout=50000&waitForConnections=true into string

set mysql_connection_string "mysql://root:pass@host?**_connectTimeout=50000&waitForConnections=true_**&charset=utf8mb4"

but its not work every time.

**Comment by renzuzu** [comment]
In what queery it does timeout?

**Comment by Velkostatkar** [comment]
I am not so skilled to answer your question so I just trying put # in server.cfg before scripts and restarting server. I literaly fishing that one who do a problem and as I make a 180x server restarts I found that when renzu_vehicleshop when is active in serverconfig it make oxmysql connection timeout to JOBS.

**Comment by Velkostatkar** [comment]
I am not so skilled to answer your question so I just trying put # in server.cfg before scripts and restarting server. I literaly fishing that one who do a problem and as I make a 180x server restarts I found that when renzu_vehicleshop when is active in serverconfig it make oxmysql connection timeout to JOBS.
