### ISSUE TITLE
Error during server start

### ISSUE THREAD

**Issue by AmFearLiath** [renzuzu/renzu_vehicleshop#39]
i want to build my server with this script, but i got this error when i start my server.

> Creating script environments for renzu_vehicleshop
Error loading script server/server.lua in resource renzu_vehicleshop: @renzu_vehicleshop/framework/sv_wrapper.lua:5: attempt to index a nil value (global 'ESX')
> stack traceback:
> @renzu_vehicleshop/framework/sv_wrapper.lua:5: in function 'Initialized'
> @renzu_vehicleshop/server/server.lua:9: in main chunk
> Failed to load script server/server.lua.
> Started resource renzu_vehicleshop

anyone can help me with this?

**Comment by SeCTioN-Master** [comment]
hm...do u have changed in config.lua your Framework?
