### ISSUE TITLE
QBCore support

### ISSUE THREAD

**Issue by Mazvis1** [renzuzu/renzu_vehicleshop#4]
Hi, is there will be a qbcore support?

**Comment by renzuzu** [comment]
maybe in future, i have to release the dealership management first.. its still WIP

**Comment by Mazvis1** [comment]
Okay, thank you

**Comment by renzuzu** [comment]
done
https://github.com/renzuzu/renzu_vehicleshop/commit/15e0e4c62961ad3e0b37942467f87ff5f50e6c6b

tell me if there is an issue
ill keep this open until then
thanks

**Comment by Mazvis1** [comment]
Okay, going to test

**Comment by Mazvis1** [comment]
Need change sql to qbcore vehicle table

>

**Comment by renzuzu** [comment]
What do you mean?

Qb core us shared vehicles right

The framework folder auto changes the owned vehicle to player vehicle table

You just need to set qbcore in config

**Comment by renzuzu** [comment]
And one thing in qbcore

I dont know how is the right logic to implement job vehicle.

So setting up a job in column via sql in esx logic will not work with qbcore.
