### ISSUE TITLE
Error on MYSQL

### ISSUE THREAD

**Issue by Novus1988** [renzuzu/renzu_vehicleshop#42]
When buy a car:

[      script:oxmysql] [ERROR] renzu_vehicleshop was unable to execute a query!
[      script:oxmysql]         Column 'vehicle' specified twice
[      script:oxmysql]         INSERT INTO player_vehicles  (license, plate, mods, `state`, job, garage, `vehicle`, `vehicle`,`hash`, `citizenid`) VALUES ('license:fcdd84332b34437c31b6ee3da6020ef3d5e883b3', 'QQH 821', '{\"modExhaust\":-1,\"wheelColor\":156,\"modFrontWheels\":-1,\"modEngineBlock\":-1,\"engineHealth\":1000.0,\"modEngine\":-1,\"dirtLevel\":8.0,\"neonColor\":[255,0,255],\"modVanityPlate\":-1,\"modSpoilers\":-1,\"modTurbo\":false,\"tankHealth\":1000.0,\"modAirFilter\":-1,\"modBrakes\":-1,\"modGrille\":-1,\"model\":719660200,\"tyreSmokeColor\":[255,255,255],\"color1\":88,\"modTank\":-1,\"modSideSkirt\":-1,\"modTrunk\":-1,\"plate\":\"QQH 821\",\"rgb2\":[119,124,135],\"modTrimA\":-1,\"modHorns\":-1,\"extras\":[],\"windowTint\":-1,\"rgb\":[245,137,15],\"wheels\":0,\"modFrame\":-1,\"modHydrolic\":-1,\"fuelLevel\":65.0,\"modPlateHolder\":-1,\"bodyHealth\":1000.0,\"modHood\":-1,\"modSeats\":-1,\"modArmor\":-1,\"modSpeakers\":-1,\"modDoorSpeaker\":-1,\"plateIndex\":0,\"modArchCover\":-1,\"modRightFender\":-1,\"modXenon\":false,\"modStruts\":-1,\"modBackWheels\":-1,\"neonEnabled\":[false,false,false,false],\"modAerials\":-1,\"modFrontBumper\":-1,\"modRoof\":-1,\"modTransmission\":-1,\"modSmokeEnabled\":false,\"color2\":5,\"modSuspension\":-1,\"modLivery\":-1,\"modOrnaments\":-1,\"modTrimB\":-1,\"modDial\":-1,\"modWindows\":-1,\"modRearBumper\":-1,\"modShifterLeavers\":-1,\"xenonColor\":255,\"modFender\":-1,\"pearlescentColor\":89,\"modAPlate\":-1,\"modSteeringWheel\":-1,\"modDashboard\":-1}', 1, false, 'A', 'ruston', 'ruston', '719660200', 'QCV03842')

**Comment by Luvlow02** [comment]
Same issue

**Comment by Hoags2510** [comment]
Is there a solution for this?

**Comment by DodgeCZE** [comment]
Same... Please help someone I literally don't know what to do with this.

**Comment by deekay-au** [comment]
If using QB, replace server.lua with https://pastebin.com/13tuN24M
