### ISSUE TITLE
Error when starting a script plus the cars don't save

### ISSUE THREAD

**Issue by The-Milo** [renzuzu/renzu_vehicleshop#51]
Hi,
I'm getting this error when the script starts (QB btw) and all the cars that I buy don't save aka don't get inserted into db

![image](https://user-images.githubusercontent.com/67521492/154546397-7bfac28f-2384-45d2-aaa5-47e010080cd2.png)

![image](https://user-images.githubusercontent.com/67521492/154546671-8473e9ba-f39b-493b-9996-2d5f6a489bcf.png)

**Comment by kelevra69** [comment]
hey im not an expert but on the 3rd line where Mysql is.....you spelt oxmysql incorrect....hope that helped
