### ISSUE TITLE
Test driving ist not good working!

### ISSUE THREAD

**Issue by CaptionPrice1** [renzuzu/renzu_vehicleshop#53]
If you gonna testdrive in the aren and jumping off the car u getting teleport to vector 0 0 0  and not back to the Vehicleshop

**Comment by CylonRaider75** [comment]
> 

I fixed it for me in the Client.lua on line 1371 with oldcoord = vector3(-50.73,-1095.35,26.42)

**Comment by Salto4501** [comment]
Bonjour @CylonRaider75  moi de mon coter a la ligne 371 il y a cela:     local count = 0 avez vous plusieurs ligne a montrer voir ou vous l'avez changer ? Merci d'avance
