### ISSUE TITLE
QBCORE car save

### ISSUE THREAD

**Issue by LightningCommunity** [renzuzu/renzu_vehicleshop#67]
cars dosn't save in qbcore server database when you punchase them.
Maybe i dont really know how to set up the shop for qbcore

**Comment by LightningCommunity** [comment]
https://prnt.sc/hGnzIv24BsRd
Im on my latest oxmysql v2.5.1

**Comment by LightningCommunity** [comment]
problem solve use v1 version of function buy and RegisterServerCallBack_('renzu_vehicleshop:buyvehicle',

**Comment by LightningCommunity** [comment]
I like the fact i fix one thing i do other thing and than something breaks

**Comment by lATVIA** [comment]
Okey soo you Can fix that by using v1 final function buy and netevent buy vehicle

**Comment by LightningCommunity** [comment]
Fixed it
