### ISSUE TITLE
Admin car

### ISSUE THREAD

**Issue by netwerin** [renzuzu/renzu_vehicleshop#75]
car not working when i spawn admin car
![image](https://user-images.githubusercontent.com/110632738/204855642-7b98a7b9-ee1c-446d-9b24-de34a26bb77d.png)

**Comment by renzuzu** [comment]
is this related to vehicleshop?

**Comment by netwerin** [comment]
Maybe renzu_garage, i dont know

**Comment by Zzeyy** [comment]
Funny, that the only issue renzuzu responds after a long time, is this one.

**Comment by renzuzu** [comment]
> Maybe renzu_garage, i dont know

then go to garage issues page.

**Comment by renzuzu** [comment]
> Funny, that the only issue renzuzu responds to after a long time, is this one.

i been gone for months last time , so all issues are not answered. i been trying to asnwer new ones only now.

and this vehicle shop is already done.

the new vehicleshop is on my other resource renzu_shops
