### ISSUE TITLE
got this error any fix?

### ISSUE THREAD

**Issue by DaRkFIR3** [renzuzu/renzu_vehicleshop#82]
[script:renzu_vehicle] SCRIPT ERROR: @renzu_vehicleshop/server/server.lua:123: bad argument #1 to 'for iterator' (table expected, got nil)
[script:renzu_vehicle] > TriggerCallback (@qb-core/server/functions.lua:249)
[script:renzu_vehicle] > handler (@qb-core/server/events.lua:146)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by renzuzu** [comment]
can you post another error , i updated the server recently , the lines are not sync anymore
