### ISSUE TITLE
error vehicleschop

### ISSUE THREAD

**Issue by Madeiradany** [renzuzu/renzu_vehicleshop#83]
Hello I have an error on your script I don't know how to fix it. Could you tell me what I have to change? 
the error occurs when I am in the vehicle shop to buy a vehicle and I have this error thank you for your help
![Capture d’écran 2023-03-12 170641](https://user-images.githubusercontent.com/83729079/224557202-ed113e9f-eef5-45e5-bdfb-bd89e56b609e.png)

**Comment by renzuzu** [comment]
use the latest main branch.. not the release download
