### ISSUE TITLE
Job vehicles spawn with the same plate

### ISSUE THREAD

**Issue by StableBarcodeDev** [renzuzu/renzu_vehicleshop#86]
Hey,  i just downloaded your script. my problem is i am using a script that counter how many kilometeres a vehicle has. but if someone buy a police car for example it will be the same plate for other people using police cars. is anyway to make the job vehicles has a Unique plate?

**Comment by renzuzu** [comment]
its should be unique each time you generate plates from shop.

how often this to happen?

**Comment by StableBarcodeDev** [comment]
i fingured out that the problem exist only if i write a plate with special characters like greek letters.  I came accross a new problem after that:

After each server restart it shows some of them and everytime different for me and other players.  For example  at 12:00AM restart it will show the first two vehicles for me but the last two vehicles for other police officers but at 04:00 AM it show the 4 last for me and the first 3 for other people.  Any idea for this? 

`['Police Vehicle Shop'] = { -- same with name
        name = "Police Vehicle Shop", --MRPD police shop
        title = "Police Vehicle Shop",
        icon = 'https://i.imgur.com/t1OPuVL.png',
        job = 'police',
        type = 'carshop',
        default_garage = 'Police Garage',
        Dist = 3, -- distance (DEPRECATED)
        Blip = {color = 38, sprite = 662, scale = 0.9},
        shop_x = 456.89453125,
        shop_y = -1020.8922729492,
        shop_z = 28.290912628174, -- coordinates for this garage
        spawn_x = 449.27224731445,
        spawn_y = -1025.3255615234,
        spawn_z = 27.905115127563,
        heading = 2.6015937328339, -- Vehicle spawn location
        plateprefix = 'elas', -- carefull using this, maximum should be 4, recommended is 3, use this only for limited vehicles, if you use this parameter in other shop, you might have a limited plates available, ex. LSPD1234 (max char of plate is 8) it means you only have 9999 vehicles possible with this LSPD
        shop = { -- if not vehicle is setup in Database SQL, we will use this
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='pol308',  name="Police Peugot 308", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='polaudia4', name="Police Audi A4", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Bike',    stock=50,price=100000,           model='polbmw',  name="Polibe BMW Z",   grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Bike',    stock=50,price=100000,           model='polbmw2',  name="Police DI.AS",  grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='pole60',  name="Police BMW E60", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='polevo9',  name="Police EVO IX", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='polevo10',  name="Police EVO X", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Pickup',  stock=50,price=100000,           model='polfrontier',  name="Police Nissan Frontier",    grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='polmazda6',  name="Police Mazda 6",  grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Van',     stock=50,price=100000,           model='polnspeedo',  name="Police Van",  grade = 0},
            {shop='Police Vehicle Shop',    brand='Police SUV',     stock=50,price=100000,           model='polqashqai',  name="Police Qashqai", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police SUV',     stock=50,price=100000,           model='polrange',  name="Police Range Rover",   grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Sedan',   stock=50,price=100000,           model='polskoda',  name="Police Skoda VRS", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police Station Wagon',stock=50,price=100000,      model='polskoda2',  name="Police Skoda VRS Station Wagon",  grade = 0},
            {shop='Police Vehicle Shop',    brand='Police SUVs',    stock=50,price=100000,           model='polskoda3',  name="Police Skoda Karoq", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police bike',    stock=50,price=100000,           model='polxt',  name="Police XT", grade = 0},
            {shop='Police Vehicle Shop',    brand='Police bike',    stock=50,price=100000,           model='polz',  name="Z Bike 2", grade = 0},

        
        
        },      
    },`

**Comment by renzuzu** [comment]
try the latest update from Main Branch.
this should keep saving New Plate Bought from vehicle shop to Temp Table.

temp table is the one making it unique

**Comment by StableBarcodeDev** [comment]
I fixed the problem with the plates by using EN character ( because still gives the same plate if i set them to GR ), but  job vehicleshops still being an issue for me. 

FIRST SERVER START
![Screenshot_22](https://user-images.githubusercontent.com/92280829/227964680-79e7eef5-340a-460e-b314-bb8494624b3b.png)

SECOND SERVER START ( AFTER RESTARTING )
![Screenshot_23](https://user-images.githubusercontent.com/92280829/227964730-1cdc3518-0357-454c-bf17-79bab34660bf.png)

**Comment by StableBarcodeDev** [comment]
Found the problem, if i got it like type = 'carshop', it only supports one category overwise it changes between categories

**Comment by renzuzu** [comment]
glad you solved it
