### ISSUE TITLE
displayed car buy menu dont ckose after buying

### ISSUE THREAD

**Issue by Timmy5314** [renzuzu/renzu_vehicleshop#89]
Yo bro, everything works very gread. Good job, i only have 1 problem the menu dont close after buying a displayed vehicle in the shop. But the code looks correct

**Comment by renzuzu** [comment]
Probably resource name is not renzu_vehicleshop

**Comment by Timmy5314** [comment]
Yes it is. I think i placed in the wrong order in my server config file is that possible. I placed after all the script ls this wrong. And i have all the overextended scripts on top is this wrong
